services:
  db:
    image: mysql:8.0
    container_name: smartfix-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartfix
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./mysql/conf.d:/etc/mysql/conf.d 

  backend:
    build: ./Backend
    container_name: smartfix-backend
    restart: always
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=smartfix-db;Port=3306;Database=smartfix;User=root;Password=root;"
    ports:
      - "5000:80"

  frontend:
    build: ./Frontend
    container_name: smartfix-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:
  